version: '2'

# Define the services/containers to be run
services:
  mmkvp: #name of your service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" #specify ports forwarding
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    container_name: mmkvp-node
    restart: always
    command: npm start
